# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  type:
    description: 'user or org'
    required: true
  name:
    description: 'user name or org name'
    required: true    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --${{ inputs.type }}
    - ${{ inputs.name }}